### ISSUE TITLE
Test fail on Linux

### ISSUE THREAD

**Issue by anatol** [jimon/premake-ninja#7]
Running tests for current HEAD (commit e51a1cb4257eb02) and it fails. See full output below.

Among other things there are message like `ninja: error: unknown target 'debug'` and `ninja: warning: multiple rules generate ninjatestprj_lib.`

```
[anatol@arch tests]$ python ./run_tests.py
-------------------------- test default setup
Building configurations...
Running action 'ninja'...
Generated build/build.ninja...
Generated build/build_ninjatestprj_debug.ninja...
Generated build/build_ninjatestprj_release.ninja...
Done (15ms).
ninja: Entering directory `build'
[4/4] link bin_debug/ninjatestprj
ninja: Entering directory `build'
ninja: error: unknown target 'debug'
FBuilding configurations...
Running action 'ninja'...
Generated build/build.ninja...
Generated build/build_ninjatestprj_debug.ninja...
Generated build/build_ninjatestprj_release.ninja...
Done (22ms).
ninja: Entering directory `build'
[5/5] link bin_debug/ninjatestprj
ninja: Entering directory `build'
ninja: error: unknown target 'debug'
FBuilding configurations...
Running action 'ninja'...
Generated build/build.ninja...
Generated build/build_ninjatestprj_debug.ninja...
Generated build/build_ninjatestprj_release.ninja...
Done (16ms).
ninja: Entering directory `build'
[2/2] link bin_release/libninjatestprj.so
FBuilding configurations...
Running action 'ninja'...
Generated build/build.ninja...
Generated build/build_ninjatestprj_app_debug.ninja...
Generated build/build_ninjatestprj_app_release.ninja...
Generated build/build_ninjatestprj_lib_test1_debug.ninja...
Generated build/build_ninjatestprj_lib_test1_release.ninja...
Generated build/build_ninjatestprj_lib_test2_debug.ninja...
Generated build/build_ninjatestprj_lib_test2_release.ninja...
Done (23ms).
ninja: Entering directory `build'
[6/6] link bin_debug/ninjatestprj_app
ninja: Entering directory `build'
ninja: error: unknown target 'debug'
FBuilding configurations...
Running action 'ninja'...
Generated build/build.ninja...
Generated build/build_ninjatestprj_debug.ninja...
Generated build/build_ninjatestprj_release.ninja...
Done (13ms).
ninja: Entering directory `build'
[2/2] ar bin_release/libninjatestprj.a
FBuilding configurations...
Running action 'ninja'...
Generated build/build.ninja...
Generated build/build_ninjatestprj_app_debug.ninja...
Generated build/build_ninjatestprj_app_release.ninja...
Generated build/build_ninjatestprj_lib test1_debug.ninja...
Generated build/build_ninjatestprj_lib test1_release.ninja...
Generated build/build_ninjatestprj_lib_test2_debug.ninja...
Generated build/build_ninjatestprj_lib_test2_release.ninja...
Done (20ms).
ninja: Entering directory `build'
ninja: warning: multiple rules generate ninjatestprj_lib. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
[6/6] link bin_debug/ninjatestprj_app
ninja: Entering directory `build'
ninja: warning: multiple rules generate ninjatestprj_lib. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
ninja: error: unknown target 'debug'
FBuilding configurations...
Running action 'ninja'...
Generated build/build.ninja...
Generated build/build_ninjatestprj_debug.ninja...
Generated build/build_ninjatestprj_release.ninja...
Done (14ms).
ninja: Entering directory `build'
[4/4] link bin_debug/ninjatestprj
ninja: Entering directory `build'
ninja: error: unknown target 'debug'
F
======================================================================
FAIL: test_include_path (__main__.TestConsoleApp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./run_tests.py", line 146, in test_include_path
    self.check_basics("build/bin_debug/ninjatestprj", "build/bin_release/ninjatestprj")
  File "./run_tests.py", line 122, in check_basics
    self.ninja("debug")
  File "./run_tests.py", line 51, in ninja
    self.assertEqual(subprocess.call(args), 0, "looks like ninja failed")
AssertionError: 1 != 0 : looks like ninja failed

======================================================================
FAIL: test_simple (__main__.TestConsoleApp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./run_tests.py", line 140, in test_simple
    self.check_basics("build/bin_debug/ninjatestprj", "build/bin_release/ninjatestprj")
  File "./run_tests.py", line 122, in check_basics
    self.ninja("debug")
  File "./run_tests.py", line 51, in ninja
    self.assertEqual(subprocess.call(args), 0, "looks like ninja failed")
AssertionError: 1 != 0 : looks like ninja failed

======================================================================
FAIL: test_simple (__main__.TestSharedLib)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./run_tests.py", line 172, in test_simple
    self.check_basics("build/bin_debug/ninjatestprj", "build/bin_release/ninjatestprj")
  File "./run_tests.py", line 118, in check_basics
    self.out_exist(out_debug)
  File "./run_tests.py", line 74, in out_exist
    os.path.exists(self.out_name(path, ".dylib", "lib"))
AssertionError: False is not true

======================================================================
FAIL: test_withapp (__main__.TestSharedLib)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./run_tests.py", line 178, in test_withapp
    self.check_basics("build/bin_debug/ninjatestprj_app", "build/bin_release/ninjatestprj_app")
  File "./run_tests.py", line 122, in check_basics
    self.ninja("debug")
  File "./run_tests.py", line 51, in ninja
    self.assertEqual(subprocess.call(args), 0, "looks like ninja failed")
AssertionError: 1 != 0 : looks like ninja failed

======================================================================
FAIL: test_simple (__main__.TestStaticLib)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./run_tests.py", line 154, in test_simple
    self.check_basics("build/bin_debug/ninjatestprj", "build/bin_release/ninjatestprj")
  File "./run_tests.py", line 118, in check_basics
    self.out_exist(out_debug)
  File "./run_tests.py", line 74, in out_exist
    os.path.exists(self.out_name(path, ".dylib", "lib"))
AssertionError: False is not true

======================================================================
FAIL: test_withapp (__main__.TestStaticLib)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./run_tests.py", line 160, in test_withapp
    self.check_basics("build/bin_debug/ninjatestprj_app", "build/bin_release/ninjatestprj_app")
  File "./run_tests.py", line 122, in check_basics
    self.ninja("debug")
  File "./run_tests.py", line 51, in ninja
    self.assertEqual(subprocess.call(args), 0, "looks like ninja failed")
AssertionError: 1 != 0 : looks like ninja failed

======================================================================
FAIL: test_simple (__main__.TestWindowedApp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./run_tests.py", line 190, in test_simple
    self.check_basics("build/bin_debug/ninjatestprj", "build/bin_release/ninjatestprj")
  File "./run_tests.py", line 122, in check_basics
    self.ninja("debug")
  File "./run_tests.py", line 51, in ninja
    self.assertEqual(subprocess.call(args), 0, "looks like ninja failed")
AssertionError: 1 != 0 : looks like ninja failed

----------------------------------------------------------------------
Ran 7 tests in 0.651s

FAILED (failures=7)
```

**Comment by jimon** [comment]
Looks like they are failing on windows as well :( I'll have a look + I'll finally setup travis/appveyor so this shouldn't repeat in the future.

**Comment by jimon** [comment]
Yep there was a problem, but it's ok now :)
